version: '3'
services:
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    restart: on-failure
  todofront:
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
    restart: on-failure
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: on-failure